const { readFile, writeFile } = require('fs/promises');
const { resolve } = require('path');

const tokensDir = resolve(__dirname, '../src/tokens');
const tokensTypeFile = resolve(__dirname, '../src/tokens/types.ts');
const packageDir = resolve(__dirname, '../');
const cssFile = resolve(packageDir, 'tokens.css');

const run = async () => {
  const [colors, corners, fonts] = await Promise.all([
    readFile(resolve(tokensDir, 'colors.json'), { encoding: 'utf-8' }),
    readFile(resolve(tokensDir, 'corners.json'), { encoding: 'utf-8' }),
    readFile(resolve(tokensDir, 'fonts.json'), { encoding: 'utf-8' }),
  ]);

  const allVars = {
    ...JSON.parse(colors).dark,
    ...JSON.parse(corners),
    ...JSON.parse(fonts),
  };

  let css = '/* generated by scripts/generate-tokens.cjs — used for IDE autocomplete */\n:root {';

  Object.entries(allVars).forEach(([name, value]) => {
    css = `${css}\n  --${name}: ${value};`;
  });

  css = `${css}\n}\n`;

  await writeFile(cssFile, css);

  let types = 'export type Tokens = {';

  Object.keys(allVars).forEach((name) => {
    types = `${types}\n  '${name}': string;`;
  });

  types = `${types}\n};\n`;

  await writeFile(tokensTypeFile, types);
};

run();
